version: '3.8'

services:
  db:
    container_name: nestjs-cicdtest
    image: mysql:latest
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: nestjs-cicdtest
      MYSQL_USER: kihwan
      MYSQL_PASSWORD: kihwan
      MYSQL_ROOT_PASSWORD: kihwan
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_data:/var/lib/mysql

